apiVersion: apps/v1 # API version for Kubernetes Deployment
kind: Deployment # Kind of Kubernetes resource we are creating
metadata:
  name: dash-pyspark-cassandra-airflow # Name of the Deployment
spec:
  selector:
    matchLabels:
      app: dash-pyspark-cassandra-airflow # Select all pods with the 'app' label set to 'dash-pyspark-cassandra-airflow'
  replicas: 1 # Number of replicas of the pod
  template:
    metadata:
      labels:
        app: dash-pyspark-cassandra-airflow # Apply the 'app' label to the pod template
    spec:
      containers:
        - name: dash # Name of the container
          image: dash-pyspark-cassandra-airflow:latest # Docker image to use for the container
          imagePullPolicy: IfNotPresent # When to pull the Docker image
          ports:
            - containerPort: 8050 # Port on which the Dash app will listen
        - name: pyspark # Name of the container
          image: dash-pyspark-cassandra-airflow:latest # Docker image to use for the container
          imagePullPolicy: IfNotPresent # When to pull the Docker image
        - name: cassandra # Name of the container
          image: cassandra:latest # Docker image to use for the container
          imagePullPolicy: IfNotPresent # When to pull the Docker image
        - name: airflow # Name of the container
          image: apache/airflow:latest # Docker image to use for the container
          imagePullPolicy: IfNotPresent # When to pull the Docker image