apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: webserver
  template:
    metadata:
      labels:
        app: airflow
        tier: webserver
    spec:
      containers:
        - name: webserver
          image: puckel/docker-airflow:2.0.2
          command: ["webserver"]
          ports:
            - containerPort: 8080
          env:
            - name: LOAD_EX
              value: "n"
          volumeMounts:
            - name: airflow-dags
              mountPath: /usr/local/airflow/dags
      volumes:
        - name: airflow-dags
          configMap:
            name: airflow-dags

---

apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: airflow
    tier: webserver

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: scheduler
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      containers:
        - name: scheduler
          image: puckel/docker-airflow:2.0.2
          command: ["scheduler"]
          env:
            - name: LOAD_EX
              value: "n"
          volumeMounts:
            - name: airflow-dags
              mountPath: /usr/local/airflow/dags
      volumes:
        - name: airflow-dags
          configMap:
            name: airflow-dags

---

apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
spec:
  ports:
    - name: scheduler
      port: 5555
      targetPort: 5555
  selector:
    app: airflow
    tier: scheduler