apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:latest
        ports:
        - containerPort: 8080
        env:
        - name: EXECUTOR
          value: Local
        - name: LOAD_EXAMPLES
          value: yes