apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: my-web:latest
        ports:
        - containerPort: 8050
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: development